# Generated by Django 5.1 on 2024-09-07 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.CharField(max_length=50)),
                ('body_color', models.CharField(max_length=50)),
                ('inside_color', models.CharField(max_length=50)),
                ('body_type', models.CharField(choices=[('passenger_car', 'سدان'), ('crossover', 'کراس اور'), ('suv', 'شاسی بلند\u200c'), ('coupe', 'كوپه'), ('hatchback', 'هاچپک'), ('convertible', 'کروک'), ('pickup', 'وانت'), ('van', 'ون')], max_length=20, null=True)),
                ('transmission', models.CharField(choices=[('automatic', 'اتوماتیک'), ('manual', 'دنده ای')], max_length=20)),
                ('fuel', models.CharField(choices=[('gasoline', 'بنزینی'), ('cng_gasoline', 'دوگانه سوز'), ('hybrid', 'هیبریدی'), ('diesel', 'دیزلی'), ('electric', 'برقی')], max_length=20)),
                ('image', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('payment_method', models.CharField(choices=[('lumpsum', 'نقدی'), ('negotiable', 'توافقی'), ('installment', 'اقساطی')], max_length=20)),
                ('seller_contact', models.CharField(max_length=100, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('free', 'رایگان'), ('premium', ',ویژه')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='ads.car')),
            ],
            options={
                'db_table': 'ad',
            },
        ),
    ]
